// using System.Text;
// using Microsoft.CodeAnalysis;
// using Microsoft.CodeAnalysis.Text;
//
// namespace GodotLib.Analyzers.SourceGenerators;
//
// [Generator]
// public sealed class InlineArrayFormatterGenerator : ISourceGenerator
// {
//     public void Initialize(GeneratorInitializationContext context) { }
//
//     public void Execute(GeneratorExecutionContext context)
//     {
//         var sb = new StringBuilder();
//
//         sb.AppendLine("""
//                       // <auto-generated/>
//                       using System;
//                       using System.Runtime.CompilerServices;
//                       
//                       using MessagePack.Formatters;
//
//                       namespace Generated.Formatters
//                       {
//                       """);
//
//         // formatters
//         for (int n = 2; n <= 16; n++)
//             sb.AppendLine(GenerateFormatter(n));
//
//         // resolver
//         sb.AppendLine(GenerateResolver());
//
//         sb.AppendLine("}");
//
//         context.AddSource(
//             "InlineArrayFormatters.g.cs",
//             SourceText.From(sb.ToString(), Encoding.UTF8)
//         );
//     }
//
//     private static string GenerateFormatter(int length)
//     {
//         return $$"""
//                  public sealed class InlineArray{{length}}Formatter<T> : IMessagePackFormatter<InlineArray{{length}}<T>>
//                  {
//                      private const int Length = {{length}};
//
//                      public void Serialize(
//                          ref MessagePackWriter writer,
//                          InlineArray{{length}}<T> value,
//                          MessagePackSerializerOptions options)
//                      {
//                          var resolver = options.Resolver;
//                          var elementFormatter = resolver.GetFormatterWithVerify<T>();
//
//                          writer.WriteArrayHeader(Length + 1);
//                          writer.Write(Length);
//
//                          for (var i = 0; i < Length; i++)
//                              elementFormatter.Serialize(ref writer, value[i], options);
//                      }
//
//                      public InlineArray{{length}}<T> Deserialize(
//                          ref MessagePackReader reader,
//                          MessagePackSerializerOptions options)
//                      {
//                          var resolver = options.Resolver;
//                          var elementFormatter = resolver.GetFormatterWithVerify<T>();
//
//                          var arrayLength = reader.ReadArrayHeader();
//                          if (arrayLength == 0)
//                              return default;
//
//                          var count = reader.ReadByte();
//                          if (count != Length)
//                              throw new InvalidOperationException(
//                                  $"InlineArray must have exactly {Length} elements");
//
//                          var value = new InlineArray{{length}}<T>();
//                          for (var i = 0; i < Length; i++)
//                              value[i] = elementFormatter.Deserialize(ref reader, options);
//
//                          return value;
//                      }
//                  }
//                  """;
//     }
//
//     private static string GenerateResolver()
//     {
//         var sb = new StringBuilder();
//
//         sb.AppendLine("""
//                       public sealed class InlineArrayResolver : IFormatterResolver
//                       {
//                           public static readonly InlineArrayResolver Instance = new();
//
//                           private InlineArrayResolver() { }
//
//                           public IMessagePackFormatter<T>? GetFormatter<T>()
//                           {
//                               return Cache<T>.Formatter;
//                           }
//
//                           private static class Cache<T>
//                           {
//                               public static readonly IMessagePackFormatter<T>? Formatter =
//                                   InlineArrayFormatterFactory<T>.Create();
//                           }
//                       }
//
//                       internal static class InlineArrayFormatterFactory<T>
//                       {
//                           public static IMessagePackFormatter<T>? Create()
//                           {
//                               var type = typeof(T);
//                               if (!type.IsGenericType)
//                                   return null;
//
//                               var def = type.GetGenericTypeDefinition();
//                               var arg = type.GetGenericArguments()[0];
//                       """);
//
//         for (int n = 2; n <= 16; n++)
//         {
//             sb.AppendLine(
//                 $"        if (def == typeof(InlineArray{n}<>)) return (IMessagePackFormatter<T>)CreateGeneric(def, arg);");
//         }
//
//         sb.AppendLine("""
//                               return null;
//                           }
//                       
//                           private static object CreateGeneric(Type formatterDef, Type arg)
//                           {
//                               var formatterType = formatterDef.MakeGenericType(arg);
//                               return Activator.CreateInstance(formatterType)!;
//                           }
//                       }
//                       """);
//
//         return sb.ToString();
//     }
// }